# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa1f23f03608ce477f6775ff5a9ada418245b1490c0151c93eb9c6f81ff59288b9f3768d44777d62bca71b9727dcbaf3179b2fd83493d8d4f1909344ffb68d2a

test:
  secret_key_base: 73eb05632a29212a65cbbec4c9b59632d68399d437143daced976c74949e87882f1f81a88a1f67f018f5ca9540697bbf4d9479d81f43bb258796fd5431fa59f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
